blueprint:
  name: Bidirectional Sonos Alarm Time Sync
  description: >
    Keeps a Sonos alarm and an input_datetime (time-only) in sync.
    Changes from Home Assistant update Sonos, and changes from the
    Sonos app update Home Assistant. Alarm is auto-enabled.
  domain: automation
  input:
    alarm_time:
      name: Input Datetime (Time Only)
      selector:
        entity:
          domain: input_datetime

    sonos_alarm_switch:
      name: Sonos Alarm Switch
      selector:
        entity:
          domain: switch

    target_sonos:
      name: Sonos Player
      selector:
        entity:
          domain: media_player

mode: single

trigger:
  - id: ha_time_changed
    platform: state
    entity_id: !input alarm_time

  - id: sonos_time_changed
    platform: state
    entity_id: !input sonos_alarm_switch

action:
  # Assign inputs to plain variables first
  - variables:
      alarm_switch_entity: !input sonos_alarm_switch
      sonos_target: !input target_sonos
      alarm_time_entity: !input alarm_time
      alarm_id: "{{ state_attr(alarm_switch_entity, 'alarm_id') }}"

  - choose:
      # -------------------------
      # HA → Sonos
      # -------------------------
      - conditions:
          - condition: trigger
            id: ha_time_changed
          - condition: template
            value_template: >
              {{ trigger.from_state is not none
                 and trigger.to_state.state
                    != state_attr(trigger.entity_id, 'time') }}
        sequence:
          - service: sonos.update_alarm
            target:
              entity_id: "{{ sonos_target }}"
            data:
              alarm_id: "{{ alarm_id }}"
              time: "{{ trigger.to_state.state }}"
              enabled: true

      # -------------------------
      # Sonos → HA
      # -------------------------
      - conditions:
          - condition: trigger
            id: sonos_time_changed
          - condition: template
            value_template: >
              {{ trigger.from_state is not none
                 and trigger.to_state.attributes.time
                    != trigger.from_state.attributes.time }}
        sequence:
          - service: input_datetime.set_datetime
            target:
              entity_id: "{{ alarm_time_entity }}"
            data:
              time: "{{ trigger.to_state.attributes.time }}"
