blueprint:
  name: Update Sonos Alarm (Data + Time)
  description: >
    Update a Sonos alarm using sonos.update_alarm.
    Accepts arbitrary service data and a time-only input for start_time.
  domain: automation

  input:
    update_time:
      name: Alarm Time
      description: Time to set the Sonos alarm to
      selector:
        time: {}

    alarm_data:
      name: Sonos Alarm Data
      description: >
        Additional data to pass to sonos.update_alarm
        (must include alarm_id)
      selector:
        object: {}

mode: single

trigger:
  - platform: time
    at: !input update_time

action:
  - service: sonos.update_alarm
    data:
      start_time: !input update_time
    data_template: !input alarm_data
