blueprint:
  name: Update Sonos Alarm from Input Datetime
  description: >
    Updates a Sonos alarm when an input_datetime (time-only) is changed.
    Automatically enables the alarm.
  domain: automation

  input:
    alarm_time:
      name: Input Datetime (Time Only)
      description: input_datetime entity used to control the alarm time
      selector:
        entity:
          domain: input_datetime

    alarm_id:
      name: Sonos Alarm ID
      description: The ID of the Sonos alarm to update
      selector:
        text: {}

    volume:
      name: Alarm Volume
      description: Optional alarm volume
      default: null
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider

    include_linked_zones:
      name: Include Linked Zones
      description: Play alarm on grouped Sonos players
      default: false
      selector:
        boolean: {}

mode: single

trigger:
  - platform: state
    entity_id: !input alarm_time

action:
  - service: sonos.update_alarm
    data:
      alarm_id: !input alarm_id
      time: "{{ states(!input alarm_time) }}"
      enabled: true
      include_linked_zones: !input include_linked_zones
      volume: >
        {% if ( !input volume ) is not none %}
        {{ !input volume }}
        {% endif %}
