blueprint:
  name: Update Sonos Alarm from Input Datetime
  description: >
    Updates a Sonos alarm when an input_datetime (time-only) is changed
    and automatically enables the alarm.
  domain: automation

  input:
    alarm_time:
      name: Input Datetime (Time Only)
      description: input_datetime entity used to control the alarm time
      selector:
        entity:
          domain: input_datetime

    target_sonos:
      name: Sonos Player
      description: Sonos media_player entity to target
      selector:
        entity:
          domain: media_player

    alarm_id:
      name: Sonos Alarm ID
      description: The ID of the Sonos alarm to update
      selector:
        text: {}

mode: single

trigger:
  - platform: state
    entity_id: !input alarm_time

action:
  - service: sonos.update_alarm
    target:
      entity_id: !input target_sonos
    data:
      alarm_id: !input alarm_id
      time: "{{ states(trigger.entity_id) }}"
      enabled: true
